
export const MESSAGES = {
  COVER_IMAGE_UPLOAD_FAILED: "Failed to upload cover image",
  COVER_IMAGE_UPDATED_SUCCESSFULLY: "Cover image updated successfully",
  COVER_IMAGE_REQUIRED: "Cover image is required",
  CURRENT_USER_AVATAR_UPDATED_SUCCESSFULLY: "User avatar updated successfully",
  CURRENT_USER_UPDATED_SUCCESSFULLY: "User updated successfully",
  CURRENT_USER_FETCHED_SUCCESSFULLY: "User fetched successfully",
  PASSWORDS_DO_NOT_MATCH: "New password and confirm password do not match",
  PASSWORD_CHANGED_SUCCESSFULLY: "Password changed successfully",
  INVALID_CURRENT_PASSWORD: "Invalid current password",
  OLD_NEW_PASSWORD_REQUIRED: "Current and new password are required",
  REFRESH_TOKEN_SUCCESSFUL: "Refresh token genrated successful",
  REFRESH_TOKEN_EXPIRED: "Refresh token has expired",
  INVALID_REFRESH_TOKEN: "Invalid refresh token",
  REQUEST_BODY_REQUIRED: "Request body is required",
  LOGOUT_SUCCESSFUL: "User logout successful",
  INVALID_ACCESS_TOKEN: "Invalid access token",
  UNAUTHORIZED_ACCESS: "Unauthorized access",
  LOGIN_SUCCESSFUL: "User Login successful",
  TOKEN_GENRATION_FAILED: "Unable to generate token",
  INVALID_USER_CREDENTIALS: "Invalid user credentials",
  USER_NOT_FOUND: "User not found",
  USERNAME_PASSWORD_REQUIRED: "Username and password are required",
  REQUIRED_FIELDS: "All fields are required",
  AVATAR_REQUIRED: "Avatar is required",
  USERNAME_ALREADY_EXISTS: "Username already exists",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  USER_REGISTRATION_FAILED: "Something went wrong while creating user",
  USER_REGISTERED_SUCCESSFULLY: "User registered successfully",
  AVATAR_UPLOAD_FAILED: "Failed to upload avatar",
  PASSWORD_REQUIRED: "Password is required",
  PASSWORD_MIN: "Password must be at least 6 characters long",
  PASSWORD_MAX: "Password must be at most 20 characters long",
};

